name: Upload files to Azure Storage

on:
    push:
        branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to blob storage
      uses: azure/CLI@v1
      env:
        AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      with:
        inlineScript: |
          az storage blob sync -c '$web' -s . --account-name '2d2d' --exclude-path 'CNAME;.git;.github'
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az cdn endpoint purge --content-paths  "/*" --profile-name "2d2d-cdn" --name "2d2d" --resource-group "2d2d"

  # Azure logout
    - name: logout
      run: |
        az logout
      if: always()